export const ROUTES = {
  HOME: '/',
  LEARN: {
    WAVE_BASICS: '/learn/wave-basics',
    LASER: '/learn/laser',
    FIBER_OPTICS: '/learn/fiber-optics',
    MODULATION_BASICS: '/learn/modulation-basics',
    INTERFERENCE: '/learn/interference',
    MZ_MODULATOR: '/learn/mz-modulator',
    IQ_MODULATOR: '/learn/iq-modulator',
    POLARIZATION: '/learn/polarization',
    NYQUIST_OFDM: '/learn/nyquist-ofdm',
    PCS_CODING: '/learn/pcs-coding',
    RECEIVER: '/learn/receiver',
    WDM_AMPLIFIER: '/learn/wdm-amplifier',
    SYSTEM_OVERVIEW: '/learn/system-overview',
    GLOSSARY: '/learn/glossary',
  },
  PLAYGROUND: {
    INTERFERENCE: '/playground/interference',
    MZ_MODULATOR: '/playground/mz-modulator',
    IQ_MODULATOR: '/playground/iq-modulator',
    POLARIZATION: '/playground/polarization',
    RECEIVER: '/playground/receiver',
  },
} as const
